### ISSUE TITLE
SECRET_KEY and OPERATION_CODE

### ISSUE THREAD

**Issue by kiendt07** [AndrewDongminYoo/segway-ble-manager#8]
Hi, how can I get the BLE_INIT_SECRET_KEY and BLE_INIT_OPERATION_CODE? Are they from Segway?

```javascript
React.useEffect(() => {
  init(BLE_INIT_SECRET_KEY, BLE_INIT_OPERATION_CODE, true);
  // get required permissions
  getRequiredPermissions();
}, []);
```

Ref: https://github.com/AndrewDongminYoo/segway-ble-manager/tree/main#simple-example-code

**Comment by AndrewDongminYoo** [comment]
@kiendt07 firstly, Thanks for first Issue!!

Yes, that's right. It's a key you can get from a company called Segway Ninebot, to be precise. 
Their website URL address is https://open.segwaydiscovery.com/documents/NBIoTBleKit/. 
Or If you're looking for a more universally available low-energy Bluetooth module that's not device manufacturer specific, 
[this package](https://github.com/innoveit/react-native-ble-manager) is a better fit.

**Comment by Azdman1978** [comment]
Is there any other way to obtain a key and op code I purchased a gen.3 iot and need to configure it for my personal use
